apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "my-nginx-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}
  custom_index.html: |
{{ .Files.Get "files/custom_index.html" | indent 4 }}
