apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-nginx-chart.fullname" . }}-service 
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "my-nginx-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "my-nginx-chart.selectorLabels" . | nindent 4 }}
