apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-nginx-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/zyusuke10/my-istio-app-gitops.git
        revision: master
        files:
          - path: "environments/**/values.yaml"
  template:
    metadata:
      name: my-nginx-{{ path[1] }} #application name per environment
      namespace: argocd
      labels:
        app.argocd.argoproj.io/applicationset-name: my-nginx-environments
    spec:
      project: default
      source:
        repoURL: https://github.com/zyusuke10/my-istio-app-gitops.git
        targetRevision: master
        path: my-nginx-chart
        helm:
          valueFiles:
            - "{{ .Files.Get path.path }} "
      destination:
        server: https://kubernetes.default.svc
        namespace: my-nginx-{{ path[1] }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true